default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: my_scrabble_development

test: &test
  <<: *default
  database: my_scrabble_test

production:
  <<: *default
  database: my_scrabble_production
  username: my_scrabble
  password: <%= ENV['MY_SCRABBLE_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
